# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_frappe.suite.ipynb (unless otherwise specified).

__all__ = ['Describe', 'It']

# Cell
from contextlib import ContextDecorator

# Cell
class Describe(ContextDecorator):
    "contextmanager to describe a test suite"
    def __init__(self, desc): store_attr('desc', self)

    def __enter__(self):
        "start the execution of the suite and do setup"
        print(self.desc)
        return self
    #TODO: create callbacks to check type, value,traceback and format report and termnial display
    def __exit__(self, type, value, traceback):
        "cleanup and exit the suite"
        print(f'{self.desc} completed')
        #print(type, value, traceback, sep="\n")
        return True

# Cell
class It(ContextDecorator):
    "contextmanager to describe a test function"
    def __init__(self, desc): store_attr('desc', self)

    def __enter__(self):
        "start the execution of the test"
        print(self.desc)
        return self
    #TODO: create callbacks to check type, value,traceback and format report and termnial display
    def __exit__(self, type, value, traceback):
        "cleanup and exit the test"
        print(f'{self.desc} completed')
        print(type, value, traceback, sep="\n")
        return True