# AUTOGENERATED! DO NOT EDIT! File to edit: 00_suite.ipynb (unless otherwise specified).

__all__ = ['describe', 'it']

# Cell
from contextlib import ContextDecorator
from dataclasses import dataclass

# Cell
@dataclass
class describe(ContextDecorator):
    "contextmanager to describe a test suite"
    desc:str

    def __enter__(self):
        "start the execution of the suite and do setup"
        print(self.desc)
        return self

    def __exit__(self, type, value, traceback):
        "cleanup and exit the suite"
        print(f'{self.desc} completed')
        print(type, value, traceback, sep="\n")
        return True

# Cell
@contextmanager
def it(desc:str):
    "describe a test with a name"
    print(desc)
    yield