# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"describe": "00_frappe.suite.ipynb",
         "it": "00_frappe.suite.ipynb"}

modules = ["frappe/suite.py"]

doc_url = "https://sapal6.github.io/Mochaccino/"

git_url = "https://github.com/sapal6/Mochaccino/tree/{branch}/"

def custom_doc_links(name): return None
